export default {
  getAllPhoto: '/api/v1/getAllPhoto',
  login: '/api/v1/login',
  logout: '/api/v1/logout',
  changeInfo: '/api/v1/user',
  uploadAvatar: '/api/v1/uploadAvatar',
  changePssword: '/api/v1/user/changePassword',
  verCode: '/api/v1/user/verificationCode',
  register: '/api/v1/user/register',
  chatChat: '/api/chat',
  chatconfig: '/api/config',
  chatProcess: '/api/chat-process',
  getUser: '/api/v1/user',
  getFriends: '/api/v1/friends',
  uploadImage: '/api/v1/uploadImage',
  uploadFile: '/api/v1/uploadFile',
  uploadPhoto: '/api/v1/uploadPhoto',
};
